version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    target-branch: "main"
    labels:
      - "Technical Dept"
    schedule:
      interval: daily
      time: "05:00"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` packages
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "05:00"
    target-branch: "main"
    labels:
      - "Technical Dept"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
