@startuml

class ContentController {
    - modeler: BpmnJS
    + constructor(modeler: BpmnJS): ContentController
    + newDiagram(): Promise<ImportWarning>
    + loadDiagram(bpmn: string): Promise<ImportWarning>
    + exportDiagram(): Promise<string>
    + getFiles(data: FolderContent[])
}

class VsCodeImpl {
    - vscode: WebviewApi<VscState>
    + constructor(): VsCodeImpl
    + getState(): VscState | undefined
    + setState(state: VscState): void
    + updateState(state: Partial<VscState>): void
    + postMessage(message: VscMessage): void
}

circle main.ts

main.ts ..|> ContentController : use
main.ts ..|> VsCodeImpl : use

@enduml
