io:
    miragon:
        miranum:
            miranum-deployment-proxy:
                deploymentHandlers:
                    local: DryHandler
                    dev: RestHandler
                    test: RestHandler
                    prod: RestHandler
                targets:
                    dev: http://localhost:39146
                    test: http://localhost:39146
                    prod: http://localhost:39146
