# Use this only in dev environments. It's not intended for production usage.
version: '3'
services:
  miranum-deployment-example:
    image: miragon/miranum-deployment-embedded-example:0.3.1-SNAPSHOT
    ports:
      - "8090:8080"
