# Copy of https://github.com/it-at-m/digiwf-core/blob/dev/stack/docker-compose.yml with miranum-specific additons

# Use this only in dev environments. It's not intended for production usage.
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Test1234
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025' # smtp server
      - '9025:8025' # ui

  digiwf-gateway:
    image: itatm/digiwf-gateway:dev
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local,local-docker,no-security
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.23.3
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:8080"
    depends_on:
      - digiwf-gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # enable the tasklist with --profile tasklist if you don't want to run it locally
  digiwf-tasklist:
    image: itatm/digiwf-tasklist:dev
    ports:
      - "8091:8080"

  miranum-deployment-proxy:
    image: miragon/miranum-deployment-proxy:latest
    ports:
      - "8090:8080"
    environment:
      IO_MIRAGON_MIRANUM_MIRANUM-DEPLOYMENT-PROXY_TARGETS_DEV: "http://host.docker.internal:39146"
      IO_MIRAGON_MIRANUM_MIRANUM-DEPLOYMENT-PROXY_DEPLOYMENTHANDLERS_DEV: "RestHandler"
    extra_hosts:
      - "host.docker.internal:host-gateway"
