@startuml
'https://plantuml.com/component-diagram

skinparam component {
  backgroundColor<<Global>> LightGray
  backgroundColor<<InAdapter>> LightGreen
  backgroundColor<<UseCase>> LightBlue
  backgroundColor<<OutAdapter>> LightYellow
}

component VsCodeBpmnEditorAdapter <<InAdapter>>
component VsCodeArtifactWatcherAdapter <<InAdapter>>

note top of [VsCodeBpmnEditorAdapter]
  main task is to ensure that the UI and
  the underlying document are in sync
end note

note left of [VsCodeArtifactWatcherAdapter]
  main task is to watch for changes in the
  artifacts (e.g., forms, element templates)
  and sync them with the UI
end note

component {
    portin DisplayModelerInPort
    portin SetArtifactInPort
    portin SetModelerSettingInPort
    portin GetMiranumConfigInPort
    portin GetWorkspaceItemInPort
    portin GetDocumentInPort
    portin SyncDocumentInPort

    portout BpmnUiOutPort
    portout BpmnModelerSettingsOutPort
    portout WorkspaceOutPort
    portout DocumentOutPort
    portout FileSystemOutPort

    component DisplayBpmnFileUseCase <<UseCase>>
    component SetFormKeysUseCase <<UseCase>>
    component SetElementTemplatesUseCase <<UseCase>>
    component SetBpmnModelerSettingsUseCase <<UseCase>>
    component GetMiranumConfigUseCase <<UseCase>>
    component GetWorkspaceItemUseCase <<UseCase>>
    component GetDocumentUseCase <<UseCase>>
    component SyncDocumentUseCase <<UseCase>>
}

component VsCodeBpmnWebviewAdapter <<OutAdapter>>
component VsCodeBpmnModelerSettingsAdapter <<OutAdapter>>
component VsCodeWorkspaceAdapter <<OutAdapter>>
component VsCodeDocumentAdapter <<OutAdapter>>
component VsCodeReadAdapter <<OutAdapter>>

'InAdapter
VsCodeBpmnEditorAdapter --> DisplayModelerInPort
VsCodeBpmnEditorAdapter --> SetArtifactInPort
VsCodeBpmnEditorAdapter --> SetModelerSettingInPort
VsCodeBpmnEditorAdapter --> SyncDocumentInPort
VsCodeBpmnEditorAdapter --> GetDocumentInPort
VsCodeBpmnEditorAdapter --> VsCodeArtifactWatcherAdapter

VsCodeArtifactWatcherAdapter --> GetDocumentInPort
VsCodeArtifactWatcherAdapter --> GetMiranumConfigInPort
VsCodeArtifactWatcherAdapter --> GetWorkspaceItemInPort
VsCodeArtifactWatcherAdapter --> SetArtifactInPort

'UseCase
DisplayBpmnFileUseCase -up-> DisplayModelerInPort
SetFormKeysUseCase -up-> SetArtifactInPort
SetElementTemplatesUseCase -up-> SetArtifactInPort
SetBpmnModelerSettingsUseCase -up-> SetModelerSettingInPort
GetMiranumConfigUseCase -up-> GetMiranumConfigInPort
GetWorkspaceItemUseCase -up-> GetWorkspaceItemInPort
GetDocumentUseCase -up-> GetDocumentInPort
SyncDocumentUseCase -up-> SyncDocumentInPort

DisplayBpmnFileUseCase -down-> BpmnUiOutPort
DisplayBpmnFileUseCase -down-> DocumentOutPort
SetFormKeysUseCase .up.> GetMiranumConfigInPort
SetFormKeysUseCase .up.> GetWorkspaceItemInPort
SetFormKeysUseCase -down-> BpmnUiOutPort
SetFormKeysUseCase -down-> DocumentOutPort
SetFormKeysUseCase -down-> FileSystemOutPort
SetElementTemplatesUseCase .up.> GetMiranumConfigInPort
SetElementTemplatesUseCase .up.> GetWorkspaceItemInPort
SetElementTemplatesUseCase -down-> BpmnUiOutPort
SetElementTemplatesUseCase -down-> DocumentOutPort
SetElementTemplatesUseCase -down-> FileSystemOutPort
SetBpmnModelerSettingsUseCase -down-> BpmnUiOutPort
SetBpmnModelerSettingsUseCase -down-> BpmnModelerSettingsOutPort
GetMiranumConfigUseCase -down-> WorkspaceOutPort
GetMiranumConfigUseCase -down-> FileSystemOutPort
GetWorkspaceItemUseCase -down-> WorkspaceOutPort
GetWorkspaceItemUseCase -down-> FileSystemOutPort
SyncDocumentUseCase -down-> DocumentOutPort
GetDocumentUseCase -down-> DocumentOutPort

VsCodeBpmnWebviewAdapter -up-> BpmnUiOutPort
VsCodeBpmnModelerSettingsAdapter -up-> BpmnModelerSettingsOutPort
VsCodeWorkspaceAdapter -up-> WorkspaceOutPort
VsCodeDocumentAdapter -up-> DocumentOutPort
VsCodeReadAdapter -up-> FileSystemOutPort

@enduml
