server:
    port: 8092
io:
    miragon:
        miranum:
            miranum-deployment-proxy:
                deployment-handlers:
                    environments:
                        -   local:
                                handler: "DryHandler"
                        -   dev:
                                handler: "RestHandler"
                                target: "http://localhost:39146/rest/"
                        -   test:
                                handler: "RestHandler"
                                target: "http://localhost:39146/rest/"
