/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    VApp: typeof import('vuetify/lib')['VApp']
    VCard: typeof import('vuetify/lib')['VCard']
    VContainer: typeof import('vuetify/lib')['VContainer']
  }
}
