@startuml

interface VsCode {
    postMessage(message: VscMessage): void;
    getState(): VscState;
    setState(state: VscState): void;
}

interface VscMessage {
    type: string;
    content: any;
}

interface VscState {
    bpmn: string;
    files: string;
}

interface FolderContent {
    type: string,
    files: JSON[] | string[]
}

Class VscController {
    - vscode: VsCode
    + getState(): void
    + setState(state: VscState): void
    + updateState(): void
    + postMessage(message: VscMessage): void
    + setListener(): void
}

Class ContentController {
    - modeler: BpmnJS
    - eventBus: any
    + constructor(modeler: BpmnJS, folderContent: FolderContent[]): ContentController
    + loadDiagram(xml: string): void
    + sendUpdate(): void
    - exportDiagram(): void
    - setListener(folderContent: FolderContent[]): void
}

Class PropertyProvider {
}

@enduml
