name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: "./coverage"
          fail_ci_if_error: true
          flags: unittests
          name: miranum-ide
          verbose: true
      - name: Build
        run: npm run build

      # docker
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_MIRAGON_USERNAME }}
          password: ${{ secrets.DOCKER_MIRAGON_PASSWORD  }}
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Maven build
        run: cd spring-boot-apps/miranum-deployment-proxy && mvn clean install -DskipTests
      - name: Build and push miranum-deployment-proxy
        uses: docker/build-push-action@v4
        with:
          context: ./spring-boot-apps/miranum-deployment-proxy
          push: true
          tags: miragon/miranum-deployment-proxy:${{ env.RELEASE_VERSION }},miragon/miranum-deployment-proxy:latest
          platforms: linux/amd64, linux/arm64/v8
