name: Dry Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  vsce-package:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Prepare
        run: npm install && npm install -g @vscode/vsce@latest
      - name: Build vsix miranum-extension-pack
        run: |
          cd dist/miranum-extension-pack
          vsce package
      - name: Build vsix miranum-console
        run: |
          cd ../miranum-console
          vsce package --out miranum-console.vsix
      - name: Build vsix miranum-forms
        run: |
          cd ../miranum-forms
          vsce package --out miranum-console.vsix
      - name: Build vsix miranum-modeler
        run: |
          cd ../miranum-modeler
          vsce package --out miranum-console.vsix
      - uses: actions/upload-artifact@v3
        with:
          name: vsix-packages
          path: dist
